/* This file is generated by zits. Do not edit manually */

import {
/** types.ts */
HoloHash,
AgentPubKey,
DnaHash,
WasmHash,
EntryHash,
ActionHash,
AnyDhtHash,
ExternalHash,
KitsuneAgent,
KitsuneSpace,
HoloHashB64,
AgentPubKeyB64,
DnaHashB64,
WasmHashB64,
EntryHashB64,
ActionHashB64,
AnyDhtHashB64,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleName,
InstalledCell,
Timestamp,
Duration,
HoloHashed,
NetworkInfo,
FetchPoolInfo,
/** hdk/action.ts */
SignedActionHashed,
RegisterAgentActivity,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** hdk/capabilities.ts */
CapSecret,
CapClaim,
GrantedFunctionsType,
GrantedFunctions,
ZomeCallCapGrant,
CapAccessType,
CapAccess,
CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** hdk/entry.ts */
EntryVisibility,
AppEntryDef,
EntryType,
EntryContent,
Entry,
/** hdk/record.ts */
Record as HcRecord,
RecordEntry as HcRecordEntry,
/** hdk/link.ts */
AnyLinkableHash,
ZomeIndex,
LinkType,
LinkTag,
RateWeight,
RateBucketId,
RateUnits,
Link,
/** api/admin/types.ts */
InstalledAppInfoStatus,
DeactivationReason,
DisabledAppReason,
StemCell,
ProvisionedCell,
ClonedCell,
CellType,
CellInfo,
AppInfo,
MembraneProof,
FunctionName,
ZomeName,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioningStrategy,
CellProvisioning,
DnaVersionSpec,
DnaVersionFlexible,
AppRoleDnaManifest,
AppRoleManifest,
AppManifest,
AppBundle,
AppBundleSource,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';

import {
/** Common */
DhtOpHashB64,
//DnaHashB64, (duplicate)
//AnyDhtHashB64, (duplicate)
DhtOpHash,
/** DnaFile */
DnaFile,
DnaDef,
Zomes,
WasmCode,
/** entry-details */
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
/** Validation */
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

/** User defined external dependencies */
import {DistributionStrategy, ParcelManifest, ParcelChunk, ParcelDescription, ParcelKind, ParcelReference} from '@ddd-qc/delivery';

export interface AttachInput {
  hrl: [DnaHash, EntryHash]
  manifestEh: EntryHash
}

export interface WriteManifestInput {
  filename: string
  filetype: string
  data_hash: string
  orig_filesize: number
  chunks: EntryHash[]
}

/**  */
export interface SendFileInput {
  manifest_eh: EntryHash
  strategy: DistributionStrategy
  recipients: AgentPubKey[]
}

/**
 * --------------------------------------------------------------------------------------------------
 * Global consts
 * --------------------------------------------------------------------------------------------------
 */
export const FILES_DEFAULT_INTEGRITY_ZOME_NAME = "files_integrity";

export const FILES_DEFAULT_COORDINATOR_ZOME_NAME = "zFiles";

export const FILES_DEFAULT_ROLE_NAME = "rFiles";

export const FILE_TYPE_NAME = "split_file";

export const ATTACHMENTS_ROOT = "public_attachments";

export enum FilesEntryType {
	FileShare = 'FileShare',
	PrivEncKey = 'PrivEncKey',
}
export type FilesEntryVariantFileShare = {FileShare: FileShare}
export type FilesEntryVariantPrivEncKey = {PrivEncKey: PrivEncKey}
export type FilesEntry = 
 | FilesEntryVariantFileShare | FilesEntryVariantPrivEncKey;

export type FilesLinkTypes =
  | {Attachment: null};
export enum FilesLinkTypesType {
	Attachment = 'Attachment',
}

/** Bogus Entry */
export interface FileShare {
  value: string
}

/** Entry representing the Private Encryption Key of an Agent */
export interface PrivEncKey {
  value: unknown
}
