/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "tagging" */
export const taggingFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"query_all_PrivateTags",
	"create_private_tag",
	"tag_private_entry",
	"get_private_tags",
	"get_private_entries_with_tag",
	"get_all_public_tags",
	"create_public_tag",
	"tag_public_entry",
	"get_public_tags",
	"get_public_entries_with_tag",];


/** Generate tuple array of function names with given zomeName */
export function generateTaggingZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of taggingFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zTagging" */
export const taggingZomeFunctions: [ZomeName, FunctionName][] = generateTaggingZomeFunctionsArray("zTagging");
