/* This file is generated by zits. Do not edit manually */

import {PUBLIC_TAG_ROOT, TAGGING_ZOME_NAME, TaggingEntry, TaggingLinkTypes, PrivateTag, TaggingInput, TaggingProperties, UntagInput, } from './tagging.types';
import {
/** types.ts */
HoloHash,
AgentPubKey,
DnaHash,
WasmHash,
EntryHash,
ActionHash,
AnyDhtHash,
ExternalHash,
KitsuneAgent,
KitsuneSpace,
HoloHashB64,
AgentPubKeyB64,
DnaHashB64,
WasmHashB64,
EntryHashB64,
ActionHashB64,
AnyDhtHashB64,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleName,
InstalledCell,
Timestamp,
Duration,
HoloHashed,
NetworkInfo,
FetchPoolInfo,
/** hdk/action.ts */
SignedActionHashed,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** hdk/capabilities.ts */
CapSecret,
CapClaim,
GrantedFunctionsType,
GrantedFunctions,
ZomeCallCapGrant,
CapAccess,
CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** hdk/entry.ts */
EntryVisibility,
AppEntryDef,
EntryType,
EntryContent,
Entry,
/** hdk/record.ts */
Record as HcRecord,
RecordEntry as HcRecordEntry,
/** api/admin/types.ts */
InstalledAppInfoStatus,
DeactivationReason,
DisabledAppReason,
StemCell,
ProvisionedCell,
ClonedCell,
CellType,
CellInfo,
AppInfo,
MembraneProof,
FunctionName,
ZomeName,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioningStrategy,
CellProvisioning,
DnaVersionSpec,
DnaVersionFlexible,
AppRoleDnaManifest,
AppRoleManifest,
AppManifest,
AppBundle,
AppBundleSource,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';

import {
/** Common */
DhtOpHashB64,
DhtOpHash,
/** DnaFile */
DnaFile,
DnaDef,
Zomes,
WasmCode,
/** entry-details */
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
/** Validation */
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {taggingFunctionNames} from './tagging.fn';

/**
 *
 */
export class TaggingProxy extends ZomeProxy {
  static readonly DEFAULT_ZOME_NAME = "zTagging"
  static readonly FN_NAMES = taggingFunctionNames
 
  async queryAllPrivateTags(): Promise<[EntryHash, Timestamp, string][]> {
    return this.call('query_all_PrivateTags', null);
  }

  async createPrivateTag(tagValue: string): Promise<EntryHash> {
    return this.call('create_private_tag', tagValue);
  }

  async tagPrivateEntry(input: TaggingInput): Promise<void> {
    return this.call('tag_private_entry', input);
  }

  async untagPrivateEntry(input: UntagInput): Promise<void> {
    return this.call('untag_private_entry', input);
  }

  async getPrivateTags(eh: EntryHash): Promise<[EntryHash, string][]> {
    return this.call('get_private_tags', eh);
  }

  async getPrivateEntriesWithTag(tag: string): Promise<[EntryHash, string][]> {
    return this.call('get_private_entries_with_tag', tag);
  }

  async getAllPublicTags(): Promise<[EntryHash, string][]> {
    return this.call('get_all_public_tags', null);
  }

  async createPublicTag(tagValue: string): Promise<EntryHash> {
    return this.call('create_public_tag', tagValue);
  }

  async tagPublicEntry(input: TaggingInput): Promise<void> {
    return this.call('tag_public_entry', input);
  }

  async getPublicTags(eh: EntryHash): Promise<string[]> {
    return this.call('get_public_tags', eh);
  }

  async getPublicEntriesWithTag(tag: string): Promise<[EntryHash, string][]> {
    return this.call('get_public_entries_with_tag', tag);
  }
}
