/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {PUBLIC_TAG_ROOT, TAGGING_ZOME_NAME, TaggingEntry, PrivateTag, TaggingInput, TaggingProperties, UntagInput, } from './tagging.types';
// @ts-ignore
import {
/** api/common.ts */
// @ts-ignore
WebsocketConnectionOptions, WsClientOptions, HolochainError, CloneIdHelper,
/** types.ts */
// @ts-ignore
KitsuneAgent, KitsuneSpace, HoloHashB64, AgentPubKeyB64, DnaHashB64, WasmHashB64, EntryHashB64, ActionHashB64, AnyDhtHashB64, InstalledAppId, Signature, CellId, DnaProperties, RoleName, InstalledCell, Timestamp, HoloHashed, FetchPoolInfo,
/** hdk/action.ts */
// @ts-ignore
SignedAction, SignedActionHashed, RegisterAgentActivity, ActionHashed, ActionType, Action, NewEntryAction, Dna, AgentValidationPkg, InitZomesComplete, CreateLink, DeleteLink, OpenChain, CloseChain, Update, Delete, Create,
/** hdk/capabilities.ts */
// @ts-ignore
CapSecret, CapClaim, GrantedFunctionsType, GrantedFunctions, ZomeCallCapGrant, CapAccess, CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
// @ts-ignore
ChainOpType, DhtOp, WarrantOp, ChainOp, Warrant, ChainIntegrityWarrant, ValidationType, ActionHashAndSig,
/** hdk/entry.ts */
// @ts-ignore
EntryVisibility, AppEntryDef, EntryType, EntryContent, Entry,
/** hdk/record.ts */
// @ts-ignore
Record as HcRecord, RecordEntry as HcRecordEntry,
/** hdk/link.ts */
//AnyLinkableHash,
// @ts-ignore
ZomeIndex, LinkType, LinkTag, RateWeight, RateBucketId, RateUnits, Link,
/** api/admin/types.ts */
// @ts-ignore
// YamlProperties
Zomes, WasmCode, CapGrantInfo, PeerMetaInfo, DisabledAppReason, AppStatus, StemCell, ProvisionedCell, ClonedCell, CellType, CellInfo, AppInfo, MembraneProof, MemproofMap, RoleSettingsMap, RoleSettings, DnaModifiersOpt, DnaModifiers, FunctionName, ZomeName, ZomeDefinition, IntegrityZome, CoordinatorZome, DnaDefinition, ResourceBytes, ResourceMap, CellProvisioningStrategy, CellProvisioning, DnaVersionSpec, DnaVersionFlexible, AppRoleDnaManifest, AppRoleManifest, AppManifest, AppBundle, AppBundleSource, NetworkSeed, AppStatusFilter, AppInterfaceInfo, AgentInfoSigned, ZomeLocation, DnaManifest,
} from '@holochain/client';


/// Simple Hashes
// @ts-ignore
type AgentArray = Uint8Array;
// @ts-ignore
type DnaArray = Uint8Array;
// @ts-ignore
type WasmArray = Uint8Array;
// @ts-ignore
type EntryArray = Uint8Array;
// @ts-ignore
type ActionArray = Uint8Array;
// @ts-ignore
type AnyDhtArray = Uint8Array;
// @ts-ignore
type AnyLinkableArray = Uint8Array;
// @ts-ignore
type ExternalArray = Uint8Array;

// @ts-ignore
import {
/** Common */
// @ts-ignore
DhtOpHashB64, DhtOpHash,
/** DnaFile */
// @ts-ignore
DnaFile, DnaDef,
/** entry-details */
// @ts-ignore
EntryDetails, RecordDetails, Details, DetailsType, EntryDhtStatus,
/** Validation */
// @ts-ignore
ValidationStatus, ValidationReceipt,
} from '@holochain-open-dev/core-types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {taggingFunctionNames} from './tagging.fn';
import {TaggingUnitEnum} from './tagging.integrity';
import {TaggingLinkType} from './tagging.integrity';

/**
 *
 */
export class TaggingProxy extends ZomeProxy {
  static override readonly DEFAULT_ZOME_NAME = "zTagging";
  static override readonly FN_NAMES = taggingFunctionNames;
  static override readonly ENTRY_TYPES = Object.values(TaggingUnitEnum);
  static override readonly LINK_TYPES = Object.values(TaggingLinkType);
 
  async queryAllPrivateTag(): Promise<[EntryArray, Timestamp, string][]> {
    return this.call('query_all_PrivateTag', null);
  }

  async commitPrivateTag(tagValue: string): Promise<EntryArray> {
    return this.callBlocking('commit_private_tag', tagValue);
  }

  async tagPrivateEntry(input: TaggingInput): Promise<void> {
    return this.call('tag_private_entry', input);
  }

  async untagPrivateEntry(input: UntagInput): Promise<void> {
    return this.callBlocking('untag_private_entry', input);
  }

  async findPrivateTagsForEntry(eh: EntryArray): Promise<[EntryArray, string][]> {
    return this.call('find_private_tags_for_entry', eh);
  }

  async findPrivateEntriesWithTag(tag: string): Promise<[EntryArray, string][]> {
    return this.call('find_private_entries_with_tag', tag);
  }

  async probePublicTags(): Promise<[EntryArray, string][]> {
    return this.call('probe_public_tags', null);
  }

  async publishPublicTag(tagValue: string): Promise<EntryArray> {
    return this.callBlocking('publish_public_tag', tagValue);
  }

  async tagPublicEntry(input: TaggingInput): Promise<ActionArray[]> {
    return this.call('tag_public_entry', input);
  }

  async findPublicTagsForEntry(eh: EntryArray): Promise<string[]> {
    return this.call('find_public_tags_for_entry', eh);
  }

  async findPublicEntriesWithTag(tag: string): Promise<[ActionArray, EntryArray, string][]> {
    return this.call('find_public_entries_with_tag', tag);
  }

  async untagPublicEntry(linkAh: ActionArray): Promise<ActionArray> {
    return this.callBlocking('untag_public_entry', linkAh);
  }
}
