[package]
name = "zome_files"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[lints]
workspace = true

[dependencies]
serde.workspace = true
hdk.workspace = true
zome_utils.workspace = true
zome_path.workspace = true
zome_core.workspace = true

zome_delivery_types.workspace = true
zome_delivery_api.workspace = true

zome_files_integrity = {path = "../files_integrity" }
